language: python
matrix:
    include:
        - python: 3.6
        - python: 3.5
        - python: 2.7

before_install:
    # Use miniconda. Taken from https://gist.github.com/dan-blanchard/7045057
    - if [[ `echo "${TRAVIS_PYTHON_VERSION}" | cut -d'.' -f1`  == "3" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
    - conda install --yes gcc_linux-64 gfortran_linux-64
    - for file in `find $HOME/miniconda/bin -name 'x86_64*'`; do ln -s $file $HOME/miniconda/bin/`echo $file | rev | cut -d'-' -f1 | rev`; done;

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy pytest six mock swig
    - if [[ `echo "${TRAVIS_PYTHON_VERSION}" | cut -d'.' -f1`  == "2" ]]; then conda update --yes setuptools; fi;
    - conda install --yes -c conda-forge coverage python-coveralls

script:
    - sed -i'' -e 's/--boxed//g' pytest.ini && coverage run --source=PyDSTool setup.py test -q

after_success:
    - coveralls --config_file .coveragerc


sudo: false
