language: python
matrix:
    include:
        - python: 3.6
          env:
            - NUMPY_SPEC=numpy
            - SCIPY_SPEC=scipy
            - COVERAGE="yes"

        - python: 3.5
          env:
            - NUMPY_SPEC=numpy
            - SCIPY_SPEC=scipy
            - COVERAGE="yes"
        - python: 2.7
          env:
            - NUMPY_SPEC=numpy
            - SCIPY_SPEC=scipy
            - COVERAGE="yes"

before_install:
    # Use miniconda. Taken from https://gist.github.com/dan-blanchard/7045057
    - if [[ `echo "${TRAVIS_PYTHON_VERSION}" | cut -d'.' -f1`  == "3" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
    - conda install --yes gcc_linux-64

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas $NUMPY_SPEC $SCIPY_SPEC pytest six mock
    - if [ "${COVERAGE}" == "yes" ]; then conda install --yes -c conda-forge coverage python-coveralls; fi

script:
    - if [ "${COVERAGE}" == "yes" ]; then sed -i'' -e 's/--boxed//g' pytest.ini && coverage run --source=PyDSTool setup.py test -q; else python setup.py test; fi

after_success:
    - if [ "${COVERAGE}" == "yes" ]; then coveralls --config_file .coveragerc; fi

cache: apt

sudo: false

addons:
    apt:
      packages:
        - swig
